### ISSUE TITLE
ERROR: for web  Container "120209d872b5" is unhealthy

### ISSUE THREAD

**Issue by xStevex** [nikhilh-20/ELFEN#1]
I'm having trouble with an error and I'm not sure how to fix it.

```
ERROR: for web  Container "120209d872b5" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

```
Docker version 20.10.17, build 100c701

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Linux remnux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nikhilh-20** [comment]
Do you have more logs from when you did a `docker compose up`? Was there some other service which failed before the `web` container was brought up? The `web` container relies on other containers to be up and properly functioning. Also, ELFEN was only tested on Ubuntu 22.04.2.

- Try recreating the docker containers. This error may be intermittent.
```bash
$ docker compose down
$ docker compose up --force-recreate
```
- Try rebuilding ELFEN from scratch
```bash
$ docker compose build --no-cache
$ docker compose up
```

**Comment by xStevex** [comment]
I tried already `docker compose up --force-recreate` and `docker compose build --no-cache` and it didn't helped.

Also, I deleted old docker and installed the newest version `Docker version 24.0.6, build ed223bc` 
In the new console, I see this message:
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/5de38f9f-02dd-4f20-a733-f126ae4b3fcb)
It looks like I have issues with the Postgres container.

Some other artifacts:
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/3de15301-eeb7-4fc7-9248-a6048214d40b)
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/fe3dea3a-c300-4b37-9a95-baf86657d6d7)
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/1f7c54d4-ff09-45f2-bca2-22ab728cf05e)

**Comment by xStevex** [comment]
I removed `user: 1000:1000 # Solves data directory permission issues`
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/b08bd4dc-f3b0-4d32-bf8e-6539bd20ae83)

and it fixed the issue.
![image](https://github.com/nikhilh-20/ELFEN/assets/27353963/f88d6b15-de11-4caa-be59-80fbda9f9e74)

**Comment by nikhilh-20** [comment]
I would highly recommend not running docker containers as `root` user as a best practice.

Your issue was caused because `data/postgres` directory was owned by `root` (you likely went through the setup instructions as `root` user). Since PostgreSQL container runs as a non-root user (`user: 1000:1000`), it was causing a permission issue in your setup.

Again, I would highly recommend not setting up / running ELFEN as `root` user.
