### ISSUE TITLE
Additional process tree in reports analysis

### ISSUE THREAD

**Issue by Namtv2312** [nikhilh-20/ELFEN#33]
I want to add some features and write a report, how can I debug code (dev) not dependent Docker environment, thanks

**Comment by nikhilh-20** [comment]
I'll write up a local setup document that should help you get ELFEN running outside docker.

**Comment by nikhilh-20** [comment]
Steps for local installation: https://github.com/nikhilh-20/ELFEN/blob/main/SETUP.md
Reopen issue if more details are required.
